spring.application.name=gyg
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/migration/V1.0.1__create_activities_table.sql,classpath:db/migration/V1.0.2__create_suppliers_table.sql